import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google"
import { ConvexClientProvider } from "@/components/convex-client-provider";
// import {NuqsAdapter} from "nuqs/adapters/next/app"
import { Toaster } from "@/components/ui/sonner";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "documentary",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets:["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <body
        className={inter.className}
      >
        {/* <NuqsAdapter> */}
        <ConvexClientProvider>
          <Toaster/>
          {children}
        </ConvexClientProvider>
        {/* </NuqsAdapter> */}
      </body>
    </html>
  );
}
